[package]
name = "rsvg_internals"
version = "0.0.1"
authors = ["Federico Mena Quintero <federico@gnome.org>"]

[dependencies]
libc = "0.2"
bitflags = ""

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo.git"
#git = "https://github.com/federicomenaquintero/cairo.git"
#git = "file:///home/federico/src/gtk-rs/cairo"
#features = ["png"]

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo.git"
#git = "https://github.com/federicomenaquintero/cairo.git"
#git = "file:///home/federico/src/gtk-rs/cairo"
#features = ["png"]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.9.3"

[dependencies.nom]
#git = "https://github.com/Geal/nom"
git = "https://github.com/federicomenaquintero/nom.git"
features = ["verbose-errors"]

[dependencies.downcast-rs]
git = "https://github.com/marcianx/downcast-rs"
version = "1.0.0"

[lib]
name = "rsvg_internals"
crate-type = ["staticlib"]
